name: webview_cookie_manager
description: Have you been turned into a cookie managment problem? This package can help. It has all of the cookie managment functionality you have been looking for.
version: 1.0.3
repository: https://github.com/amag2511/webview_cookie_manager
homepage: https://github.com/amag2511/webview_cookie_manager
issue_tracker: https://github.com/amag2511/webview_cookie_manager/issues
# documentation: link on documentation

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_cookie_manager_platform_interface: 
    path: ../webview_cookie_manager_platform_interface
  webview_cookie_manager_web: 
    path: ../webview_cookie_manager_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webview_cookie_manager
        pluginClass: WebviewCookieManagerPlugin
      ios:
        pluginClass: WebviewCookieManagerPlugin
